// {
//     {
//       "token": "***",
//       "job": "build",
//       "ref": "refs/heads/master",
//       "sha": "c4d3b0e1f065ec620078542768d044920ee72582",
//       "repository": "babakDoraniArab/react-app-github-actions",
//       "repository_owner": "babakDoraniArab",
//       "repository_owner_id": "40353024",
//       "repositoryUrl": "git://github.com/babakDoraniArab/react-app-github-actions.git",
//       "run_id": "2243957116",
//       "run_number": "57",
//       "retention_days": "90",
//       "run_attempt": "1",
//       "artifact_cache_size_limit": "10",
//       "repository_id": "485709324",
//       "actor_id": "40353024",
//       "actor": "babakDoraniArab",
//       "workflow": "CI",
//       "head_ref": "",
//       "base_ref": "",
//       "event_name": "push",
//       "event": {
//         "after": "c4d3b0e1f065ec620078542768d044920ee72582",
//         "base_ref": null,
//         "before": "3cb25c61266759c5c079b34ec0796775efa1c545",
//         "commits": [
//           {
//             "author": {
//               "email": "babak.dorani@gmail.com",
//               "name": "Babak Doraniarab",
//               "username": "babakDoraniArab"
//             },
//             "committer": {
//               "email": "babak.dorani@gmail.com",
//               "name": "Babak Doraniarab",
//               "username": "babakDoraniArab"
//             },
//             "distinct": true,
//             "id": "c4d3b0e1f065ec620078542768d044920ee72582",
//             "message": "fix(test): get the github context",
//             "timestamp": "2022-04-29T10:24:11+03:00",
//             "tree_id": "86a333f7554e48972083dc36b9ca4d2d632063ea",
//             "url": "https://github.com/babakDoraniArab/react-app-github-actions/commit/c4d3b0e1f065ec620078542768d044920ee72582"
//           }
//         ],
//         "compare": "https://github.com/babakDoraniArab/react-app-github-actions/compare/3cb25c612667...c4d3b0e1f065",
//         "created": false,
//         "deleted": false,
//         "forced": false,
//         "head_commit": {
//           "author": {
//             "email": "babak.dorani@gmail.com",
//             "name": "Babak Doraniarab",
//             "username": "babakDoraniArab"
//           },
//           "committer": {
//             "email": "babak.dorani@gmail.com",
//             "name": "Babak Doraniarab",
//             "username": "babakDoraniArab"
//           },
//           "distinct": true,
//           "id": "c4d3b0e1f065ec620078542768d044920ee72582",
//           "message": "fix(test): get the github context",
//           "timestamp": "2022-04-29T10:24:11+03:00",
//           "tree_id": "86a333f7554e48972083dc36b9ca4d2d632063ea",
//           "url": "https://github.com/babakDoraniArab/react-app-github-actions/commit/c4d3b0e1f065ec620078542768d044920ee72582"
//         },
//         "pusher": {
//           "email": "babak.dorani@gmail.com",
//           "name": "babakDoraniArab"
//         },
//         "ref": "refs/heads/master",
//         "repository": {
//           "allow_forking": true,
//           "archive_url": "https://api.github.com/repos/babakDoraniArab/react-app-github-actions/{archive_format}{/ref}",
//           "archived": false,
//           "assignees_url": "https://api.github.com/repos/babakDoraniArab/react-app-github-actions/assignees{/user}",
//           "blobs_url": "https://api.github.com/repos/babakDoraniArab/react-app-github-actions/git/blobs{/sha}",
//           "branches_url": "https://api.github.com/repos/babakDoraniArab/react-app-github-actions/branches{/branch}",
//           "clone_url": "https://github.com/babakDoraniArab/react-app-github-actions.git",
//           "collaborators_url": "https://api.github.com/repos/babakDoraniArab/react-app-github-actions/collaborators{/collaborator}",
//           "comments_url": "https://api.github.com/repos/babakDoraniArab/react-app-github-actions/comments{/number}",
//           "commits_url": "https://api.github.com/repos/babakDoraniArab/react-app-github-actions/commits{/sha}",
//           "compare_url": "https://api.github.com/repos/babakDoraniArab/react-app-github-actions/compare/{base}...{head}",
//           "contents_url": "https://api.github.com/repos/babakDoraniArab/react-app-github-actions/contents/{+path}",
//           "contributors_url": "https://api.github.com/repos/babakDoraniArab/react-app-github-actions/contributors",
//           "created_at": 1650963662,
//           "default_branch": "master",
//           "deployments_url": "https://api.github.com/repos/babakDoraniArab/react-app-github-actions/deployments",
//           "description": null,
//           "disabled": false,
//           "downloads_url": "https://api.github.com/repos/babakDoraniArab/react-app-github-actions/downloads",
//           "events_url": "https://api.github.com/repos/babakDoraniArab/react-app-github-actions/events",
//           "fork": false,
//           "forks": 0,
//           "forks_count": 0,
//           "forks_url": "https://api.github.com/repos/babakDoraniArab/react-app-github-actions/forks",
//           "full_name": "babakDoraniArab/react-app-github-actions",
//           "git_commits_url": "https://api.github.com/repos/babakDoraniArab/react-app-github-actions/git/commits{/sha}",
//           "git_refs_url": "https://api.github.com/repos/babakDoraniArab/react-app-github-actions/git/refs{/sha}",
//           "git_tags_url": "https://api.github.com/repos/babakDoraniArab/react-app-github-actions/git/tags{/sha}",
//           "git_url": "git://github.com/babakDoraniArab/react-app-github-actions.git",
//           "has_downloads": true,
//           "has_issues": true,
//           "has_pages": false,
//           "has_projects": true,
//           "has_wiki": true,
//           "homepage": null,
//           "hooks_url": "https://api.github.com/repos/babakDoraniArab/react-app-github-actions/hooks",
//           "html_url": "https://github.com/babakDoraniArab/react-app-github-actions",
//           "id": 485709324,
//           "is_template": false,
//           "issue_comment_url": "https://api.github.com/repos/babakDoraniArab/react-app-github-actions/issues/comments{/number}",
//           "issue_events_url": "https://api.github.com/repos/babakDoraniArab/react-app-github-actions/issues/events{/number}",
//           "issues_url": "https://api.github.com/repos/babakDoraniArab/react-app-github-actions/issues{/number}",
//           "keys_url": "https://api.github.com/repos/babakDoraniArab/react-app-github-actions/keys{/key_id}",
//           "labels_url": "https://api.github.com/repos/babakDoraniArab/react-app-github-actions/labels{/name}",
//           "language": "JavaScript",
//           "languages_url": "https://api.github.com/repos/babakDoraniArab/react-app-github-actions/languages",
//           "license": null,
//           "master_branch": "master",
//           "merges_url": "https://api.github.com/repos/babakDoraniArab/react-app-github-actions/merges",
//           "milestones_url": "https://api.github.com/repos/babakDoraniArab/react-app-github-actions/milestones{/number}",
//           "mirror_url": null,
//           "name": "react-app-github-actions",
//           "node_id": "R_kgDOHPNWDA",
//           "notifications_url": "https://api.github.com/repos/babakDoraniArab/react-app-github-actions/notifications{?since,all,participating}",
//           "open_issues": 4,
//           "open_issues_count": 4,
//           "owner": {
//             "avatar_url": "https://avatars.githubusercontent.com/u/40353024?v=4",
//             "email": "babak.dorani@gmail.com",
//             "events_url": "https://api.github.com/users/babakDoraniArab/events{/privacy}",
//             "followers_url": "https://api.github.com/users/babakDoraniArab/followers",
//             "following_url": "https://api.github.com/users/babakDoraniArab/following{/other_user}",
//             "gists_url": "https://api.github.com/users/babakDoraniArab/gists{/gist_id}",
//             "gravatar_id": "",
//             "html_url": "https://github.com/babakDoraniArab",
//             "id": 40353024,
//             "login": "babakDoraniArab",
//             "name": "babakDoraniArab",
//             "node_id": "MDQ6VXNlcjQwMzUzMDI0",
//             "organizations_url": "https://api.github.com/users/babakDoraniArab/orgs",
//             "received_events_url": "https://api.github.com/users/babakDoraniArab/received_events",
//             "repos_url": "https://api.github.com/users/babakDoraniArab/repos",
//             "site_admin": false,
//             "starred_url": "https://api.github.com/users/babakDoraniArab/starred{/owner}{/repo}",
//             "subscriptions_url": "https://api.github.com/users/babakDoraniArab/subscriptions",
//             "type": "User",
//             "url": "https://api.github.com/users/babakDoraniArab"
//           },
//           "private": false,
//           "pulls_url": "https://api.github.com/repos/babakDoraniArab/react-app-github-actions/pulls{/number}",
//           "pushed_at": 1651217057,
//           "releases_url": "https://api.github.com/repos/babakDoraniArab/react-app-github-actions/releases{/id}",
//           "size": 431,
//           "ssh_url": "git@github.com:babakDoraniArab/react-app-github-actions.git",
//           "stargazers": 0,
//           "stargazers_count": 0,
//           "stargazers_url": "https://api.github.com/repos/babakDoraniArab/react-app-github-actions/stargazers",
//           "statuses_url": "https://api.github.com/repos/babakDoraniArab/react-app-github-actions/statuses/{sha}",
//           "subscribers_url": "https://api.github.com/repos/babakDoraniArab/react-app-github-actions/subscribers",
//           "subscription_url": "https://api.github.com/repos/babakDoraniArab/react-app-github-actions/subscription",
//           "svn_url": "https://github.com/babakDoraniArab/react-app-github-actions",
//           "tags_url": "https://api.github.com/repos/babakDoraniArab/react-app-github-actions/tags",
//           "teams_url": "https://api.github.com/repos/babakDoraniArab/react-app-github-actions/teams",
//           "topics": [],
//           "trees_url": "https://api.github.com/repos/babakDoraniArab/react-app-github-actions/git/trees{/sha}",
//           "updated_at": "2022-04-26T09:01:45Z",
//           "url": "https://github.com/babakDoraniArab/react-app-github-actions",
//           "visibility": "public",
//           "watchers": 0,
//           "watchers_count": 0
//         },
//         "sender": {
//           "avatar_url": "https://avatars.githubusercontent.com/u/40353024?v=4",
//           "events_url": "https://api.github.com/users/babakDoraniArab/events{/privacy}",
//           "followers_url": "https://api.github.com/users/babakDoraniArab/followers",
//           "following_url": "https://api.github.com/users/babakDoraniArab/following{/other_user}",
//           "gists_url": "https://api.github.com/users/babakDoraniArab/gists{/gist_id}",
//           "gravatar_id": "",
//           "html_url": "https://github.com/babakDoraniArab",
//           "id": 40353024,
//           "login": "babakDoraniArab",
//           "node_id": "MDQ6VXNlcjQwMzUzMDI0",
//           "organizations_url": "https://api.github.com/users/babakDoraniArab/orgs",
//           "received_events_url": "https://api.github.com/users/babakDoraniArab/received_events",
//           "repos_url": "https://api.github.com/users/babakDoraniArab/repos",
//           "site_admin": false,
//           "starred_url": "https://api.github.com/users/babakDoraniArab/starred{/owner}{/repo}",
//           "subscriptions_url": "https://api.github.com/users/babakDoraniArab/subscriptions",
//           "type": "User",
//           "url": "https://api.github.com/users/babakDoraniArab"
//         }
//       },
//       "server_url": "https://github.com",
//       "api_url": "https://api.github.com",
//       "graphql_url": "https://api.github.com/graphql",
//       "ref_name": "master",
//       "ref_protected": false,
//       "ref_type": "branch",
//       "secret_source": "Actions",
//       "workspace": "/home/runner/work/react-app-github-actions/react-app-github-actions",
//       "action": "github_context_step",
//       "event_path": "/home/runner/work/_temp/_github_workflow/event.json",
//       "action_repository": "",
//       "action_ref": "",
//       "path": "/home/runner/work/_temp/_runner_file_commands/add_path_044d76a3-3134-4720-b258-3d39480a43ec",
//       "env": "/home/runner/work/_temp/_runner_file_commands/set_env_044d76a3-3134-4720-b258-3d39480a43ec",
//       "step_summary": "/home/runner/work/_temp/_runner_file_commands/step_summary_044d76a3-3134-4720-b258-3d39480a43ec"
//     }
// }