name: CI
on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
# cache node_modules      
      - name: Cache node_modules
        uses: actions/cache@v1
        with: 
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      # check the actions/cache for different languages
          restore-keys: |
            ${{ runner.os }}-node-
      # if github don't find a cache with the key, it will go to find any old cache with  ${{ runner.os }}-node- structure and then it will use it and cached it one more time. 

#use Nodejs and run it     
      - name: Use NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm ci
      - run: npm run format
      - run: npm test -- --coverage
        env:
          CI: true
#upload test coverage artifact           
      - name: upload test artifact
        uses: actions/upload-artifact@v1
        with:
          name: code coverage
          path: coverage  
#Build project             
      - name: Build project
        if: github.event_name == 'push'
        run: npm run build
#upload project Folder
      - name: upload build Folder
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v1
        with:
          name: build Folder
          path: build   
#Deploy project Folder
      - name: Deploy to Staging
        if: github.event_name == 'push'
        run: npx surge --project ./build --domain Û¶
        env:
          SURGE_LOGIN: ${{secrets.SURGE_LOGIN}}
          SURGE_TOKEN: ${{secrets.SURGE_TOKEN}}
